program: experiments/train_simple.py
method: grid # Bayesian optimization for efficient search
project: neural-network-numpy
name: fashion_mnist_sweep_kasper

metric:
  name: val_loss
  goal: minimize

parameters:
  optimizer:
    values: [sgd, adam, rmsprop] # Test different optimizers
  l2_lambda:
    values: [0.01, 0.001, 0.0001] # Larger regularization
  learning_rate:
    values: [0.01, 0.001, 0.0001]
  hidden_layers:
    values: [[64, 32, 16], [256, 128, 64, 32], [512, 256, 128, 64]]
  batch_size:
    value: 64
  activation:
    values: [relu, adam, sigmoid] # Test different activations
  output_activation:
    value: softmax
  num_epochs:
    value: 60 # Grid search requires discrete values
  weight_init:
    values: [he, random] # Test different initializations
  dropout_rate:
    values: [0.2, 0.1]
  num_epochs:
    value: 40
  dataset:
    value: fashion_mnist # Fixed to Fashion-MNIST
  output_size:
    value: 10
  val_split:
    value: 0.2
  random_seed:
    value: 42
  use_wandb:
    value: true